### ISSUE TITLE
CFMinimal dependency is private

### ISSUE THREAD

**Issue by wesrobb** [dewf/opendl#2]
Hi,

I saw your post on the Nim forums and wanted to try out opendl. Cloning the repo with submodules fails due to the fact that CFMinimal appears to be marked as a private repo. This change was made here: [https://github.com/dewf/opendl/commit/62a0344199f59bc67e5d7609785774d195f18502](https://github.com/dewf/opendl/commit/62a0344199f59bc67e5d7609785774d195f18502)

Is this intentional?

**Comment by dewf** [comment]
Oops! Thank you for bringing that to my attention. I briefly had everything private and forgot to make that one public again. Should be fixed now - let me know if you have any other questions in trying to use it!

**Comment by wesrobb** [comment]
Thanks!

**Comment by wesrobb** [comment]
Thanks!
